#pragma once

struct Dissemination;
struct ReqUserLogin;
struct RspUserLogin;
struct UserLogout;
struct ForceUserLogout;
struct ReqAuthenticate;
struct RspAuthenticate;
struct AuthenticationInfo;
struct RspUserLogin2;
struct TransferHeader;
struct TransferBankToFutureReq;
struct TransferBankToFutureRsp;
struct TransferFutureToBankReq;
struct TransferFutureToBankRsp;
struct TransferQryBankReq;
struct TransferQryBankRsp;
struct TransferQryDetailReq;
struct TransferQryDetailRsp;
struct RspInfo;
struct Exchange;
struct Product;
struct Instrument;
struct Broker;
struct Trader;
struct Investor;
struct TradingCode;
struct PartBroker;
struct SuperUser;
struct SuperUserFunction;
struct InvestorGroup;
struct TradingAccount;
struct InvestorPosition;
struct InstrumentMarginRate;
struct InstrumentCommissionRate;
struct DepthMarketData;
struct InstrumentTradingRight;
struct BrokerUser;
struct BrokerUserPassword;
struct BrokerUserFunction;
struct TraderOffer;
struct SettlementInfo;
struct InstrumentMarginRateAdjust;
struct ExchangeMarginRate;
struct ExchangeMarginRateAdjust;
struct ExchangeRate;
struct SettlementRef;
struct CurrentTime;
struct CommPhase;
struct LoginInfo;
struct LogoutAll;
struct FrontStatus;
struct UserPasswordUpdate;
struct InputOrder;
struct Order;
struct ExchangeOrder;
struct ExchangeOrderInsertError;
struct InputOrderAction;
struct OrderAction;
struct ExchangeOrderAction;
struct ExchangeOrderActionError;
struct ExchangeTrade;
struct Trade;
struct UserSession;
struct QryMaxOrderVolume;
struct SettlementInfoConfirm;
struct SyncDeposit;
struct SyncFundMortgage;
struct BrokerSync;
struct SyncingInvestor;
struct SyncingTradingCode;
struct SyncingInvestorGroup;
struct SyncingTradingAccount;
struct SyncingInvestorPosition;
struct SyncingInstrumentMarginRate;
struct SyncingInstrumentCommissionRate;
struct SyncingInstrumentTradingRight;
struct QryOrder;
struct QryTrade;
struct QryInvestorPosition;
struct QryTradingAccount;
struct QryInvestor;
struct QryTradingCode;
struct QryInvestorGroup;
struct QryInstrumentMarginRate;
struct QryInstrumentCommissionRate;
struct QryInstrumentTradingRight;
struct QryBroker;
struct QryTrader;
struct QrySuperUserFunction;
struct QryUserSession;
struct QryPartBroker;
struct QryFrontStatus;
struct QryExchangeOrder;
struct QryOrderAction;
struct QryExchangeOrderAction;
struct QrySuperUser;
struct QryExchange;
struct QryProduct;
struct QryInstrument;
struct QryDepthMarketData;
struct QryBrokerUser;
struct QryBrokerUserFunction;
struct QryTraderOffer;
struct QrySyncDeposit;
struct QrySettlementInfo;
struct QryExchangeMarginRate;
struct QryExchangeMarginRateAdjust;
struct QryExchangeRate;
struct QrySyncFundMortgage;
struct QryHisOrder;
struct OptionInstrMiniMargin;
struct OptionInstrMarginAdjust;
struct OptionInstrCommRate;
struct OptionInstrTradeCost;
struct QryOptionInstrTradeCost;
struct QryOptionInstrCommRate;
struct IndexPrice;
struct InputExecOrder;
struct InputExecOrderAction;
struct ExecOrder;
struct ExecOrderAction;
struct QryExecOrder;
struct ExchangeExecOrder;
struct QryExchangeExecOrder;
struct QryExecOrderAction;
struct ExchangeExecOrderAction;
struct QryExchangeExecOrderAction;
struct ErrExecOrder;
struct QryErrExecOrder;
struct ErrExecOrderAction;
struct QryErrExecOrderAction;
struct OptionInstrTradingRight;
struct QryOptionInstrTradingRight;
struct InputForQuote;
struct ForQuote;
struct QryForQuote;
struct ExchangeForQuote;
struct QryExchangeForQuote;
struct InputQuote;
struct InputQuoteAction;
struct Quote;
struct QuoteAction;
struct QryQuote;
struct ExchangeQuote;
struct QryExchangeQuote;
struct QryQuoteAction;
struct ExchangeQuoteAction;
struct QryExchangeQuoteAction;
struct OptionInstrDelta;
struct ForQuoteRsp;
struct StrikeOffset;
struct QryStrikeOffset;
struct InputBatchOrderAction;
struct BatchOrderAction;
struct ExchangeBatchOrderAction;
struct QryBatchOrderAction;
struct CombInstrumentGuard;
struct QryCombInstrumentGuard;
struct InputCombAction;
struct CombAction;
struct QryCombAction;
struct ExchangeCombAction;
struct QryExchangeCombAction;
struct ProductExchRate;
struct QryProductExchRate;
struct QryForQuoteParam;
struct ForQuoteParam;
struct MMOptionInstrCommRate;
struct QryMMOptionInstrCommRate;
struct MMInstrumentCommissionRate;
struct QryMMInstrumentCommissionRate;
struct InstrumentOrderCommRate;
struct QryInstrumentOrderCommRate;
struct TradeParam;
struct InstrumentMarginRateUL;
struct FutureLimitPosiParam;
struct LoginForbiddenIP;
struct IPList;
struct InputOptionSelfClose;
struct InputOptionSelfCloseAction;
struct OptionSelfClose;
struct OptionSelfCloseAction;
struct QryOptionSelfClose;
struct ExchangeOptionSelfClose;
struct QryOptionSelfCloseAction;
struct ExchangeOptionSelfCloseAction;
struct SyncDelaySwap;
struct QrySyncDelaySwap;
struct InvestUnit;
struct QryInvestUnit;
struct SecAgentCheckMode;
struct SecAgentTradeInfo;
struct MarketData;
struct MarketDataBase;
struct MarketDataStatic;
struct MarketDataLastMatch;
struct MarketDataBestPrice;
struct MarketDataBid23;
struct MarketDataAsk23;
struct MarketDataBid45;
struct MarketDataAsk45;
struct MarketDataUpdateTime;
struct MarketDataBandingPrice;
struct MarketDataExchange;
struct SpecificInstrument;
struct InstrumentStatus;
struct QryInstrumentStatus;
struct InvestorAccount;
struct PositionProfitAlgorithm;
struct Discount;
struct QryTransferBank;
struct TransferBank;
struct QryInvestorPositionDetail;
struct InvestorPositionDetail;
struct TradingAccountPassword;
struct MDTraderOffer;
struct QryMDTraderOffer;
struct QryNotice;
struct Notice;
struct UserRight;
struct QrySettlementInfoConfirm;
struct LoadSettlementInfo;
struct BrokerWithdrawAlgorithm;
struct TradingAccountPasswordUpdateV1;
struct TradingAccountPasswordUpdate;
struct QryCombinationLeg;
struct QrySyncStatus;
struct CombinationLeg;
struct SyncStatus;
struct QryLinkMan;
struct LinkMan;
struct QryBrokerUserEvent;
struct BrokerUserEvent;
struct QryContractBank;
struct ContractBank;
struct InvestorPositionCombineDetail;
struct ParkedOrder;
struct ParkedOrderAction;
struct QryParkedOrder;
struct QryParkedOrderAction;
struct RemoveParkedOrder;
struct RemoveParkedOrderAction;
struct InvestorWithdrawAlgorithm;
struct QryInvestorPositionCombineDetail;
struct MarketDataAveragePrice;
struct VerifyInvestorPassword;
struct UserIP;
struct TradingNoticeInfo;
struct TradingNotice;
struct QryTradingNotice;
struct QryErrOrder;
struct ErrOrder;
struct ErrorConditionalOrder;
struct QryErrOrderAction;
struct ErrOrderAction;
struct QryExchangeSequence;
struct ExchangeSequence;
struct QryMaxOrderVolumeWithPrice;
struct QryBrokerTradingParams;
struct BrokerTradingParams;
struct QryBrokerTradingAlgos;
struct BrokerTradingAlgos;
struct QueryBrokerDeposit;
struct BrokerDeposit;
struct QryCFMMCBrokerKey;
struct CFMMCBrokerKey;
struct CFMMCTradingAccountKey;
struct QryCFMMCTradingAccountKey;
struct BrokerUserOTPParam;
struct ManualSyncBrokerUserOTP;
struct CommRateModel;
struct QryCommRateModel;
struct MarginModel;
struct QryMarginModel;
struct EWarrantOffset;
struct QryEWarrantOffset;
struct QryInvestorProductGroupMargin;
struct InvestorProductGroupMargin;
struct QueryCFMMCTradingAccountToken;
struct CFMMCTradingAccountToken;
struct QryProductGroup;
struct ProductGroup;
struct Bulletin;
struct QryBulletin;
struct MulticastInstrument;
struct QryMulticastInstrument;
struct AppIDAuthAssign;
struct ReqOpenAccount;
struct ReqCancelAccount;
struct ReqChangeAccount;
struct ReqTransfer;
struct RspTransfer;
struct ReqRepeal;
struct RspRepeal;
struct ReqQueryAccount;
struct RspQueryAccount;
struct FutureSignIO;
struct RspFutureSignIn;
struct ReqFutureSignOut;
struct RspFutureSignOut;
struct ReqQueryTradeResultBySerial;
struct RspQueryTradeResultBySerial;
struct ReqDayEndFileReady;
struct ReturnResult;
struct VerifyFuturePassword;
struct VerifyCustInfo;
struct VerifyFuturePasswordAndCustInfo;
struct DepositResultInform;
struct ReqSyncKey;
struct RspSyncKey;
struct NotifyQueryAccount;
struct TransferSerial;
struct QryTransferSerial;
struct NotifyFutureSignIn;
struct NotifyFutureSignOut;
struct NotifySyncKey;
struct QryAccountRegister;
struct AccountRegister;
struct OpenAccount;
struct CancelAccount;
struct ChangeAccount;
struct SecAgentACIDMap;
struct QrySecAgentACIDMap;
struct UserRightsAssign;
struct BrokerUserRightAssign;
struct DRTransfer;
struct FensUserInfo;
struct CurrTransferIdentity;
struct LoginForbiddenUser;
struct QryLoginForbiddenUser;
struct TradingAccountReserve;
struct QryLoginForbiddenIP;
struct QryIPList;
struct QryUserRightsAssign;
struct ReserveOpenAccountConfirm;
struct ReserveOpenAccount;
struct AccountProperty;
struct QryCurrDRIdentity;
struct CurrDRIdentity;
struct QrySecAgentCheckMode;
struct QrySecAgentTradeInfo;
struct ReqUserAuthMethod;
struct RspUserAuthMethod;
struct ReqGenUserCaptcha;
struct RspGenUserCaptcha;
struct ReqGenUserText;
struct RspGenUserText;
struct ReqUserLoginWithCaptcha;
struct ReqUserLoginWithText;
struct ReqUserLoginWithOTP;
struct ReqApiHandshake;
struct RspApiHandshake;
struct ReqVerifyApiKey;
struct DepartmentUser;
struct QueryFreq;
struct AuthForbiddenIP;
struct QryAuthForbiddenIP;
struct SyncDelaySwapFrozen;
struct UserSystemInfo;
struct AuthUserID;
struct AuthIP;
struct QryClassifiedInstrument;
struct QryCombPromotionParam;
struct CombPromotionParam;
struct ReqUserLoginSM;
struct QryRiskSettleInvestPosition;
struct QryRiskSettleProductStatus;
struct RiskSettleInvestPosition;
struct RiskSettleProductStatus;
struct SyncDeltaInfo;
struct SyncDeltaProductStatus;
struct SyncDeltaInvstPosDtl;
struct SyncDeltaInvstPosCombDtl;
struct SyncDeltaTradingAccount;
struct SyncDeltaInitInvstMargin;
struct SyncDeltaDceCombInstrument;
struct SyncDeltaInvstMarginRate;
struct SyncDeltaExchMarginRate;
struct SyncDeltaOptExchMargin;
struct SyncDeltaOptInvstMargin;
struct SyncDeltaInvstMarginRateUL;
struct SyncDeltaOptInvstCommRate;
struct SyncDeltaInvstCommRate;
struct SyncDeltaProductExchRate;
struct SyncDeltaDepthMarketData;
struct SyncDeltaIndexPrice;
struct SyncDeltaEWarrantOffset;
struct SPBMFutureParameter;
struct SPBMOptionParameter;
struct SPBMIntraParameter;
struct SPBMInterParameter;
struct SyncSPBMParameterEnd;
struct QrySPBMFutureParameter;
struct QrySPBMOptionParameter;
struct QrySPBMIntraParameter;
struct QrySPBMInterParameter;
struct SPBMPortfDefinition;
struct SPBMInvestorPortfDef;
struct InvestorPortfMarginRatio;
struct QrySPBMPortfDefinition;
struct QrySPBMInvestorPortfDef;
struct QryInvestorPortfMarginRatio;
struct InvestorProdSPBMDetail;
struct QryInvestorProdSPBMDetail;
struct PortfTradeParamSetting;
struct InvestorTradingRight;
struct MortgageParam;
struct WithDrawParam;
struct ThostUserFunction;
struct QryThostUserFunction;
struct SPBMAddOnInterParameter;
struct QrySPBMAddOnInterParameter;
struct QryInvestorCommoditySPMMMargin;
struct QryInvestorCommodityGroupSPMMMargin;
struct QrySPMMInstParam;
struct QrySPMMProductParam;
struct InvestorCommoditySPMMMargin;
struct InvestorCommodityGroupSPMMMargin;
struct SPMMInstParam;
struct SPMMProductParam;
struct QryTraderAssign;
struct TraderAssign;
struct InvestorInfoCntSetting;
struct RCAMSCombProductInfo;
struct RCAMSInstrParameter;
struct RCAMSIntraParameter;
struct RCAMSInterParameter;
struct RCAMSShortOptAdjustParam;
struct RCAMSInvestorCombPosition;
struct InvestorProdRCAMSMargin;
struct QryRCAMSCombProductInfo;
struct QryRCAMSInstrParameter;
struct QryRCAMSIntraParameter;
struct QryRCAMSInterParameter;
struct QryRCAMSShortOptAdjustParam;
struct QryRCAMSInvestorCombPosition;
struct QryInvestorProdRCAMSMargin;
struct RULEInstrParameter;
struct RULEIntraParameter;
struct RULEInterParameter;
struct QryRULEInstrParameter;
struct QryRULEIntraParameter;
struct QryRULEInterParameter;
struct InvestorProdRULEMargin;
struct QryInvestorProdRULEMargin;
struct SyncDeltaSPBMPortfDefinition;
struct SyncDeltaSPBMInvstPortfDef;
struct SyncDeltaSPBMFutureParameter;
struct SyncDeltaSPBMOptionParameter;
struct SyncDeltaSPBMIntraParameter;
struct SyncDeltaSPBMInterParameter;
struct SyncDeltaSPBMAddOnInterParam;
struct SyncDeltaSPMMInstParam;
struct SyncDeltaSPMMProductParam;
struct SyncDeltaInvestorSPMMModel;
struct SyncDeltaSPMMModelParam;
struct SyncDeltaRCAMSCombProdInfo;
struct SyncDeltaRCAMSInstrParameter;
struct SyncDeltaRCAMSIntraParameter;
struct SyncDeltaRCAMSInterParameter;
struct SyncDeltaRCAMSSOptAdjParam;
struct SyncDeltaRCAMSCombRuleDtl;
struct SyncDeltaRCAMSInvstCombPos;
struct SyncDeltaRULEInstrParameter;
struct SyncDeltaRULEIntraParameter;
struct SyncDeltaRULEInterParameter;
struct IpAddrParam;
struct QryIpAddrParam;
struct TGIpAddrParam;
struct QryTGIpAddrParam;
struct TGSessionQryStatus;
struct LocalAddrConfig;
struct QryLocalAddrConfig;
struct ReqQueryBankAccountBySec;
struct RspQueryBankAccountBySec;
struct ReqTransferBySec;
struct RspTransferBySec;
struct NotifyQueryFutureAccountBySec;
struct ExitEmergency;
struct InvestorPortfMarginModel;
struct InvestorPortfSetting;
struct QryInvestorPortfSetting;
struct UserPasswordUpdateFromSec;
struct SettlementInfoConfirmFromSec;
struct TradingAccountPasswordUpdateFromSec;
struct RiskForbiddenRight;
struct InvestorInfoCommRec;
struct QryInvestorInfoCommRec;
struct CombLeg;
struct QryCombLeg;
struct InputOffsetSetting;
struct OffsetSetting;
struct CancelOffsetSetting;
struct QryOffsetSetting;
struct AddrAppIDRelation;
struct QryAddrAppIDRelation;
struct WechatUserSystemInfo;
struct InvestorReserveInfo;
struct QryInvestorDepartmentFlat;
struct InvestorDepartmentFlat;
struct QryDepartmentUser;
struct FrontInfo;

struct TraderApi;
struct TraderSpi;
class CTraderSpi;

#include "ctp-rs/src/lib.rs.h"
#include "ctp-rs/wrapper/include/CTraderSpi.h"
#include "ThostFtdcMdApi.h"
#include "ThostFtdcTraderApi.h"

#if defined(__APPLE__) && defined(CTP_RS_DARWIN_TRADER_DLOPEN)
// On the macOS-dlopen build the dylib's vtable was compiled against the
// darwin 6.7.7 SDK (125 API methods). Calling through the linux-shaped
// CThostFtdcTraderApi vtable (133 methods, with extras inserted at slots
// 14, 15, 51) would dispatch every slot >= 14 to the wrong dylib method.
// Holding the api pointer typed as the shim makes the compiler emit
// vtable-index calls that match the dylib's actual layout.
#include "ctp-rs/wrapper/include/DarwinSdkShim.h"
using CtpRsTraderApiBase = CThostFtdcTraderApiDarwinShim;
#else
using CtpRsTraderApiBase = CThostFtdcTraderApi;
#endif

#include "rust/cxx.h"
#include <memory>

struct TraderApi {
    TraderApi(rust::Box<TraderSpi> gateway, rust::String flow_path, bool is_production_mode);
    ~TraderApi();
    FrontInfo GetFrontInfo() const;

    rust::String get_api_version() const;
    void init() const;
    int32_t join() const;
    rust::String get_trading_day() const;
    void register_front(rust::String front_address) const;
    void register_name_server(rust::String ns_address) const;
    void register_fens_user_info(FensUserInfo fens_user_info) const;
    void subscribe_private_topic(int32_t resume_type) const;
    void subscribe_public_topic(int32_t resume_type) const;
    int32_t req_authenticate(ReqAuthenticate req_authenticate, int32_t request_id) const;
    int32_t register_user_system_info(UserSystemInfo user_system_info) const;
    int32_t submit_user_system_info(UserSystemInfo user_system_info) const;
    int32_t register_wechat_user_system_info(WechatUserSystemInfo user_system_info) const;
    int32_t submit_wechat_user_system_info(WechatUserSystemInfo user_system_info) const;
    int32_t req_user_login(ReqUserLogin req_user_login, int32_t request_id) const;
    int32_t req_user_logout(UserLogout user_logout, int32_t request_id) const;
    int32_t req_user_password_update(UserPasswordUpdate user_password_update, int32_t request_id) const;
    int32_t req_trading_account_password_update(TradingAccountPasswordUpdate trading_account_password_update, int32_t request_id) const;
    int32_t req_user_auth_method(ReqUserAuthMethod req_user_auth_method, int32_t request_id) const;
    int32_t req_gen_user_captcha(ReqGenUserCaptcha req_gen_user_captcha, int32_t request_id) const;
    int32_t req_gen_user_text(ReqGenUserText req_gen_user_text, int32_t request_id) const;
    int32_t req_user_login_with_captcha(ReqUserLoginWithCaptcha req_user_login_with_captcha, int32_t request_id) const;
    int32_t req_user_login_with_text(ReqUserLoginWithText req_user_login_with_text, int32_t request_id) const;
    int32_t req_user_login_with_otp(ReqUserLoginWithOTP req_user_login_with_otp, int32_t request_id) const;
    int32_t req_order_insert(InputOrder input_order, int32_t request_id) const;
    int32_t req_parked_order_insert(ParkedOrder parked_order, int32_t request_id) const;
    int32_t req_parked_order_action(ParkedOrderAction parked_order_action, int32_t request_id) const;
    int32_t req_order_action(InputOrderAction input_order_action, int32_t request_id) const;
    int32_t req_qry_max_order_volume(QryMaxOrderVolume qry_max_order_volume, int32_t request_id) const;
    int32_t req_settlement_info_confirm(SettlementInfoConfirm settlement_info_confirm, int32_t request_id) const;
    int32_t req_remove_parked_order(RemoveParkedOrder remove_parked_order, int32_t request_id) const;
    int32_t req_remove_parked_order_action(RemoveParkedOrderAction remove_parked_order_action, int32_t request_id) const;
    int32_t req_exec_order_insert(InputExecOrder input_exec_order, int32_t request_id) const;
    int32_t req_exec_order_action(InputExecOrderAction input_exec_order_action, int32_t request_id) const;
    int32_t req_for_quote_insert(InputForQuote input_for_quote, int32_t request_id) const;
    int32_t req_quote_insert(InputQuote input_quote, int32_t request_id) const;
    int32_t req_quote_action(InputQuoteAction input_quote_action, int32_t request_id) const;
    int32_t req_batch_order_action(InputBatchOrderAction input_batch_order_action, int32_t request_id) const;
    int32_t req_option_self_close_insert(InputOptionSelfClose input_option_self_close, int32_t request_id) const;
    int32_t req_option_self_close_action(InputOptionSelfCloseAction input_option_self_close_action, int32_t request_id) const;
    int32_t req_comb_action_insert(InputCombAction input_comb_action, int32_t request_id) const;
    int32_t req_qry_order(QryOrder qry_order, int32_t request_id) const;
    int32_t req_qry_trade(QryTrade qry_trade, int32_t request_id) const;
    int32_t req_qry_investor_position(QryInvestorPosition qry_investor_position, int32_t request_id) const;
    int32_t req_qry_trading_account(QryTradingAccount qry_trading_account, int32_t request_id) const;
    int32_t req_qry_investor(QryInvestor qry_investor, int32_t request_id) const;
    int32_t req_qry_trading_code(QryTradingCode qry_trading_code, int32_t request_id) const;
    int32_t req_qry_instrument_margin_rate(QryInstrumentMarginRate qry_instrument_margin_rate, int32_t request_id) const;
    int32_t req_qry_instrument_commission_rate(QryInstrumentCommissionRate qry_instrument_commission_rate, int32_t request_id) const;
    int32_t req_qry_user_session(QryUserSession qry_user_session, int32_t request_id) const;
    int32_t req_qry_exchange(QryExchange qry_exchange, int32_t request_id) const;
    int32_t req_qry_product(QryProduct qry_product, int32_t request_id) const;
    int32_t req_qry_instrument(QryInstrument qry_instrument, int32_t request_id) const;
    int32_t req_qry_depth_market_data(QryDepthMarketData qry_depth_market_data, int32_t request_id) const;
    int32_t req_qry_trader_offer(QryTraderOffer qry_trader_offer, int32_t request_id) const;
    int32_t req_qry_settlement_info(QrySettlementInfo qry_settlement_info, int32_t request_id) const;
    int32_t req_qry_transfer_bank(QryTransferBank qry_transfer_bank, int32_t request_id) const;
    int32_t req_qry_investor_position_detail(QryInvestorPositionDetail qry_investor_position_detail, int32_t request_id) const;
    int32_t req_qry_notice(QryNotice qry_notice, int32_t request_id) const;
    int32_t req_qry_settlement_info_confirm(QrySettlementInfoConfirm qry_settlement_info_confirm, int32_t request_id) const;
    int32_t req_qry_investor_position_combine_detail(QryInvestorPositionCombineDetail qry_investor_position_combine_detail, int32_t request_id) const;
    int32_t req_qry_cfmmc_trading_account_key(QryCFMMCTradingAccountKey qry_cfmmc_trading_account_key, int32_t request_id) const;
    int32_t req_qry_ewarrant_offset(QryEWarrantOffset qry_ewarrant_offset, int32_t request_id) const;
    int32_t req_qry_investor_product_group_margin(QryInvestorProductGroupMargin qry_investor_product_group_margin, int32_t request_id) const;
    int32_t req_qry_exchange_margin_rate(QryExchangeMarginRate qry_exchange_margin_rate, int32_t request_id) const;
    int32_t req_qry_exchange_margin_rate_adjust(QryExchangeMarginRateAdjust qry_exchange_margin_rate_adjust, int32_t request_id) const;
    int32_t req_qry_exchange_rate(QryExchangeRate qry_exchange_rate, int32_t request_id) const;
    int32_t req_qry_sec_agent_acid_map(QrySecAgentACIDMap qry_sec_agent_acid_map, int32_t request_id) const;
    int32_t req_qry_product_exch_rate(QryProductExchRate qry_product_exch_rate, int32_t request_id) const;
    int32_t req_qry_product_group(QryProductGroup qry_product_group, int32_t request_id) const;
    int32_t req_qry_mm_instrument_commission_rate(QryMMInstrumentCommissionRate qry_mm_instrument_commission_rate, int32_t request_id) const;
    int32_t req_qry_mm_option_instr_comm_rate(QryMMOptionInstrCommRate qry_mm_option_instr_comm_rate, int32_t request_id) const;
    int32_t req_qry_instrument_order_comm_rate(QryInstrumentOrderCommRate qry_instrument_order_comm_rate, int32_t request_id) const;
    int32_t req_qry_sec_agent_trading_account(QryTradingAccount qry_trading_account, int32_t request_id) const;
    int32_t req_qry_sec_agent_check_mode(QrySecAgentCheckMode qry_sec_agent_check_mode, int32_t request_id) const;
    int32_t req_qry_sec_agent_trade_info(QrySecAgentTradeInfo qry_sec_agent_trade_info, int32_t request_id) const;
    int32_t req_qry_option_instr_trade_cost(QryOptionInstrTradeCost qry_option_instr_trade_cost, int32_t request_id) const;
    int32_t req_qry_option_instr_comm_rate(QryOptionInstrCommRate qry_option_instr_comm_rate, int32_t request_id) const;
    int32_t req_qry_exec_order(QryExecOrder qry_exec_order, int32_t request_id) const;
    int32_t req_qry_for_quote(QryForQuote qry_for_quote, int32_t request_id) const;
    int32_t req_qry_quote(QryQuote qry_quote, int32_t request_id) const;
    int32_t req_qry_option_self_close(QryOptionSelfClose qry_option_self_close, int32_t request_id) const;
    int32_t req_qry_invest_unit(QryInvestUnit qry_invest_unit, int32_t request_id) const;
    int32_t req_qry_comb_instrument_guard(QryCombInstrumentGuard qry_comb_instrument_guard, int32_t request_id) const;
    int32_t req_qry_comb_action(QryCombAction qry_comb_action, int32_t request_id) const;
    int32_t req_qry_transfer_serial(QryTransferSerial qry_transfer_serial, int32_t request_id) const;
    int32_t req_qry_account_register(QryAccountRegister qry_account_register, int32_t request_id) const;
    int32_t req_qry_contract_bank(QryContractBank qry_contract_bank, int32_t request_id) const;
    int32_t req_qry_parked_order(QryParkedOrder qry_parked_order, int32_t request_id) const;
    int32_t req_qry_parked_order_action(QryParkedOrderAction qry_parked_order_action, int32_t request_id) const;
    int32_t req_qry_trading_notice(QryTradingNotice qry_trading_notice, int32_t request_id) const;
    int32_t req_qry_broker_trading_params(QryBrokerTradingParams qry_broker_trading_params, int32_t request_id) const;
    int32_t req_qry_broker_trading_algos(QryBrokerTradingAlgos qry_broker_trading_algos, int32_t request_id) const;
    int32_t req_query_cfmmc_trading_account_token(QueryCFMMCTradingAccountToken query_cfmmc_trading_account_token, int32_t request_id) const;
    int32_t req_from_bank_to_future_by_future(ReqTransfer req_transfer, int32_t request_id) const;
    int32_t req_from_future_to_bank_by_future(ReqTransfer req_transfer, int32_t request_id) const;
    int32_t req_query_bank_account_money_by_future(ReqQueryAccount req_query_account, int32_t request_id) const;
    int32_t req_qry_classified_instrument(QryClassifiedInstrument qry_classified_instrument, int32_t request_id) const;
    int32_t req_qry_comb_promotion_param(QryCombPromotionParam qry_comb_promotion_param, int32_t request_id) const;
    int32_t req_qry_risk_settle_invest_position(QryRiskSettleInvestPosition qry_risk_settle_invest_position, int32_t request_id) const;
    int32_t req_qry_risk_settle_product_status(QryRiskSettleProductStatus qry_risk_settle_product_status, int32_t request_id) const;
    int32_t req_qry_spbm_future_parameter(QrySPBMFutureParameter qry_spbm_future_parameter, int32_t request_id) const;
    int32_t req_qry_spbm_option_parameter(QrySPBMOptionParameter qry_spbm_option_parameter, int32_t request_id) const;
    int32_t req_qry_spbm_intra_parameter(QrySPBMIntraParameter qry_spbm_intra_parameter, int32_t request_id) const;
    int32_t req_qry_spbm_inter_parameter(QrySPBMInterParameter qry_spbm_inter_parameter, int32_t request_id) const;
    int32_t req_qry_spbm_portf_definition(QrySPBMPortfDefinition qry_spbm_portf_definition, int32_t request_id) const;
    int32_t req_qry_spbm_investor_portf_def(QrySPBMInvestorPortfDef qry_spbm_investor_portf_def, int32_t request_id) const;
    int32_t req_qry_investor_portf_margin_ratio(QryInvestorPortfMarginRatio qry_investor_portf_margin_ratio, int32_t request_id) const;
    int32_t req_qry_investor_prod_spbm_detail(QryInvestorProdSPBMDetail qry_investor_prod_spbm_detail, int32_t request_id) const;
    int32_t req_qry_investor_commodity_spmm_margin(QryInvestorCommoditySPMMMargin qry_investor_commodity_spmm_margin, int32_t request_id) const;
    int32_t req_qry_investor_commodity_group_spmm_margin(QryInvestorCommodityGroupSPMMMargin qry_investor_commodity_group_spmm_margin, int32_t request_id) const;
    int32_t req_qry_spmm_inst_param(QrySPMMInstParam qry_spmm_inst_param, int32_t request_id) const;
    int32_t req_qry_spmm_product_param(QrySPMMProductParam qry_spmm_product_param, int32_t request_id) const;
    int32_t req_qry_spbm_add_on_inter_parameter(QrySPBMAddOnInterParameter qry_spbm_add_on_inter_parameter, int32_t request_id) const;
    int32_t req_qry_rcams_comb_product_info(QryRCAMSCombProductInfo qry_rcams_comb_product_info, int32_t request_id) const;
    int32_t req_qry_rcams_instr_parameter(QryRCAMSInstrParameter qry_rcams_instr_parameter, int32_t request_id) const;
    int32_t req_qry_rcams_intra_parameter(QryRCAMSIntraParameter qry_rcams_intra_parameter, int32_t request_id) const;
    int32_t req_qry_rcams_inter_parameter(QryRCAMSInterParameter qry_rcams_inter_parameter, int32_t request_id) const;
    int32_t req_qry_rcams_short_opt_adjust_param(QryRCAMSShortOptAdjustParam qry_rcams_short_opt_adjust_param, int32_t request_id) const;
    int32_t req_qry_rcams_investor_comb_position(QryRCAMSInvestorCombPosition qry_rcams_investor_comb_position, int32_t request_id) const;
    int32_t req_qry_investor_prod_rcams_margin(QryInvestorProdRCAMSMargin qry_investor_prod_rcams_margin, int32_t request_id) const;
    int32_t req_qry_rule_instr_parameter(QryRULEInstrParameter qry_rule_instr_parameter, int32_t request_id) const;
    int32_t req_qry_rule_intra_parameter(QryRULEIntraParameter qry_rule_intra_parameter, int32_t request_id) const;
    int32_t req_qry_rule_inter_parameter(QryRULEInterParameter qry_rule_inter_parameter, int32_t request_id) const;
    int32_t req_qry_investor_prod_rule_margin(QryInvestorProdRULEMargin qry_investor_prod_rule_margin, int32_t request_id) const;
    int32_t req_qry_investor_portf_setting(QryInvestorPortfSetting qry_investor_portf_setting, int32_t request_id) const;
    int32_t req_qry_investor_info_comm_rec(QryInvestorInfoCommRec qry_investor_info_comm_rec, int32_t request_id) const;
    int32_t req_qry_comb_leg(QryCombLeg qry_comb_leg, int32_t request_id) const;
    int32_t req_offset_setting(InputOffsetSetting input_offset_setting, int32_t request_id) const;
    int32_t req_cancel_offset_setting(InputOffsetSetting input_offset_setting, int32_t request_id) const;
    int32_t req_qry_offset_setting(QryOffsetSetting qry_offset_setting, int32_t request_id) const;

    CtpRsTraderApiBase *api;
    CTraderSpi *spi;
};

std::unique_ptr<TraderApi> CreateTraderApi(rust::Box<TraderSpi> gateway, rust::String flow_path, bool is_production_mode);
